services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    CedricWagner\PageEditorBundle\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']